version: '3'
services:
  helloworldarm:
    image: hivetechnologies/helloworldarm
    environment:
      WEBPAGESTRING: "This is helloworld on ARM"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet

networks:
  webnet: