version: '3'
services:
  helloworldarm:
    image: hivetechnologies/helloworldarm
    environment:
      WEBPAGESTRING: "This is helloworld on ARM"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:8080"
    networks:
      - webnet

  visualizer:
    image: alexellis2/visualizer-arm
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:8080/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

networks:
  webnet: